language: rust
rust:
    - nightly
before_install:
    - sudo pip install -r pb-jelly-gen/requirements.txt
    - PROTOBUF_VERSION=3.7.1
    - PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
    - mkdir /tmp/protoc_install
    - pushd /tmp/protoc_install
    - wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
    - unzip ${PROTOC_FILENAME}
    - bin/protoc --version
    - sudo cp bin/* /usr/local/bin/
    - sudo cp -r include/* /usr/local/include/
    - popd
script:
    - set -e
    - protoc --version
    # unit tests
    - cd pb-jelly
    - cargo test --verbose
    - cd ../pb-jelly-gen
    - cargo test --verbose
     pbtest
    - cd ../pb-test/pb_test_gen
    - cargo run
    - cd ..
    - cargo test --verbose
     examples
    - cd ../examples/examples_gen
    - cargo run
    - cd ..
    - cargo test --verbose
