language: rust
rust:
    - nightly
addons:
    apt:
        packages:
            - "python3-pip"
before_install:
    - sudo pip install -r pb-jelly-gen/requirements.txt
    - python3 -m pip install mypy==0.782 mypy-protobuf==1.23
    - rustup component add rustfmt
    - PROTOBUF_VERSION=3.7.1
    - PROTOC_FILENAME=protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
    - mkdir /tmp/protoc_install
    - pushd /tmp/protoc_install
    - wget https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/${PROTOC_FILENAME}
    - unzip ${PROTOC_FILENAME}
    - bin/protoc --version
    - sudo cp bin/* /usr/local/bin/
    - sudo cp -r include/* /usr/local/include/
    - popd
script:
    - set -e
    - protoc --version

    # Run mypy on codegen.py
    - cd pb-jelly-gen/codegen
    - protoc --mypy_out=proto rust/extensions.proto
    - mypy .
    - cd ../..

    # Rustfmt
    - for d in examples pb-jelly pb-jelly-gen pb-test; do cd $d ; cargo fmt -- --check ; cd .. ; done

    # unit tests
    - cd pb-jelly
    - cargo test --verbose
    - cd ../pb-jelly-gen
    - cargo test --verbose
    # pbtest
    - cd ../pb-test/pb_test_gen
    - cargo run
    - cd ..
    - cargo test --verbose
    # examples
    - cd ../examples/examples_gen
    - cargo run
    - cd ..
    - cargo test --verbose
