[tool.setuptools]
py-modules = ["codegen", "proto"]

[project]
name = "codegen"
version = "0.0.1"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
