name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rustfmt:
    name: Check formatting with rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Run rustfmt
        run: ci/run_rustfmt.sh
  mypy:
    name: Run mypy on codegen.py
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.17.3'
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - run: ci/run_mypy.sh
