name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rustfmt:
    name: Check formatting with rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Run rustfmt
        run: |
          set -x
          cargo --version
          cargo fmt --version
          for d in examples pb-jelly pb-jelly-gen pb-test
          do
            pushd $d
            cargo fmt -- --check
            popd
          done
